version: "3"
services:
  app:
    container_name: ms_carrito
    restart: always
    build: .
    volumes:
      - "./api:/app/"
    ports:
      - "127.0.0.1:80:3000"
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ../mongodb/data:/data/db
      - ../mongodb/mongoconfig:/data/configd
    ports:
      - "127.0.0.1:27017:27017"